In [1]:
l=[1,2,3]

In [2]:
import numpy as np

In [39]:
arr=np.array(l)

In [40]:
arr

array([1, 2, 3])

In [41]:
l2=[[1,2,3],[4,5,6],[7,8,9]]

In [42]:
np.array(l2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.arange(0,5,1)

array([0, 1, 2, 3, 4])

In [44]:
np.zeros(4)


array([0., 0., 0., 0.])

In [45]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [47]:
np.ones((5,0))

array([], shape=(5, 0), dtype=float64)

In [48]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
np.random.rand(5,2)

array([[0.06915625, 0.48539472],
       [0.17284864, 0.73902936],
       [0.06257789, 0.35386702],
       [0.05637173, 0.88481083],
       [0.11791335, 0.87877516]])

In [51]:
np.random.randn(5,2)

array([[-0.89245914,  0.97461152],
       [-0.26398051, -1.07773967],
       [ 1.75437857,  0.56354533],
       [-1.06691404, -0.73342446],
       [-0.4415746 ,  0.93410414]])

In [54]:
np.random.randint(2,9,6)

array([3, 5, 6, 8, 3, 4])

In [55]:
arr=np.arange(25)

In [61]:
rarr=np.random.randint(0,50,10)

In [62]:
rarr

array([25, 14, 45,  3, 36, 30, 24, 14,  3, 43])

In [58]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
rarr.argmin()

3

In [33]:
rarr

array([18, 36, 26, 37, 36, 14, 15, 16,  9,  0])

In [32]:
rarr.max()

37

In [34]:
arr=arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [64]:
type(arr)

numpy.ndarray

In [65]:
arr.dtype

dtype('int32')

In [67]:
rr=np.random.randint(3,13,10)

In [68]:
rr[:6]

array([6, 7, 7, 6, 4, 7])

In [69]:
rr[:6]

array([6, 7, 7, 6, 4, 7])

In [70]:
rr[0:5]=100

In [71]:
rr

array([100, 100, 100, 100, 100,   7,   4,  10,  11,  11])

In [72]:
cc=np.arange(1,11)

In [73]:
cc>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
cc[cc>5]

array([ 6,  7,  8,  9, 10])

In [75]:
x=np.array([1,2,3,4,5,6])

In [76]:
x*100

array([100, 200, 300, 400, 500, 600])